In [1]:
import numpy as np

a = np.loadtxt('a.txt')
pes = np.loadtxt('w.txt')

a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [2]:
w = pes.T[0].reshape(3,3)
w

array([[ 10., -13.,  16.],
       [-42.,  92.,  79.],
       [ -5.,  71.,  33.]])

In [5]:
pes

array([[ 10., -11.,  12.],
       [-13.,  14., -15.],
       [ 16., -17.,  18.],
       [-42.,  65.,  17.],
       [ 92., -23.,  41.],
       [ 79.,  11., -64.],
       [ -5.,  38.,  27.],
       [ 71., -19.,   8.],
       [ 33.,  54., -29.]])

In [4]:
from scipy.signal import convolve2d

ans = []
for i in range(3):
    w = pes.T[i].reshape(3,3)
    o = convolve2d(a,w[::-1].T[::-1].T,mode='valid')
    ans.append(o)
ans

[array([[2282., 2523., 2764.],
        [3487., 3728., 3969.],
        [4692., 4933., 5174.]]),
 array([[1175., 1287., 1399.],
        [1735., 1847., 1959.],
        [2295., 2407., 2519.]]),
 array([[-71., -56., -41.],
        [  4.,  19.,  34.],
        [ 79.,  94., 109.]])]